openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/register:
    post:
      summary: Register
      operationId: register
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n \"name\": \"Adetunji Phillip\",\n \"email\": \"phillip@mail.com\",\n}"
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the user.'
                  example: 'Adetunji Phillip'
                email:
                  type: string
                  description: 'The email of the user.'
                  example: phillip@email.com
                password:
                  type: string
                  description: 'The password of the user.'
                  example: '12345678'
              required:
                - name
                - email
                - password
      security: []
  /api/login:
    post:
      summary: Register
      operationId: register
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email of the user.'
                  example: sakinropo@gmail.com
                password:
                  type: string
                  description: 'The password of the user.'
                  example: '12345678'
              required:
                - email
                - password
      security: []
  /api/profile:
    get:
      summary: ''
      operationId: getApiProfile
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Authentication
      security: []
  /api/logout:
    get:
      summary: ''
      operationId: getApiLogout
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Authentication
      security: []
  /api/customers:
    post:
      summary: ''
      operationId: postApiCustomers
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: eguy
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: gkassulke@example.net
                phone:
                  type: string
                  description: 'Must not be greater than 20 characters.'
                  example: xjpmbkumhpc
                address:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: gplrywubepavuwznvkjpkocmg
              required:
                - name
                - email
      security: []
    get:
      summary: ''
      operationId: getApiCustomers
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/customers/{id}':
    get:
      summary: ''
      operationId: getApiCustomersId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiCustomersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: v
                email:
                  type: string
                  description: ''
                  example: null
                phone:
                  type: string
                  description: 'Must not be greater than 20 characters.'
                  example: giwvejoheqrsqouq
                address:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: oyvjdebvrmpnqjbse
              required:
                - name
      security: []
    delete:
      summary: ''
      operationId: deleteApiCustomersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the customer.'
        example: dolorem
        required: true
        schema:
          type: string
tags:
  -
    name: Authentication
    description: "\nAPIs for user authentication"
  -
    name: Endpoints
    description: ''
